name: blender-kb
services:
  ingest:
    build:
      context: .
      dockerfile: ./src/ingest/ingest.Dockerfile
    container_name: blender-kb-ingest
    volumes:
      - ingest_data:/app               
      # - ./data/vectors:/app/data/vectors
      # - ./data/raw:/app/data/raw
      - ./data:/app/data
    # ports:
    #   - "3000:3000"
    environment:
      - APP_ENV=ingest
      - DB_ROOT= /app/data/vectors/blender_api_index
      - PYTHONUNBUFFERED=1
    networks:
      - blender-kb-network
    profiles: ["manual"]

  chromadb:
    image: chromadb/chroma
    container_name: blender-kb-chromadb
    ports:
      - ":8000"
    volumes:
      - ./data/vectors/blender_api_index:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v2/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - blender-kb-network

  ollama:
    build:
      context: .
      dockerfile: ./src/ollama/ollama.Dockerfile
    container_name: blender-kb-ollama
    # ports:
    #   - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama               
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://0.0.0.0:11434/api/tags || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped
    networks:
      - blender-kb-network

  mcp-server:
    build:
      context: .
      dockerfile: ./src/mcp-server/mcp.Dockerfile
    container_name: blender-kb-mcp
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=mcp
      - FASTMCP_HOST=0.0.0.0
      - FASTMCP_PORT=8000
    restart: unless-stopped
    networks:
      - blender-kb-network
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - temp_data:/data

networks:
  blender-kb-network:
    driver: bridge

volumes:
  temp_data:
  ingest_data:
  chromadb_data:
  ollama_data:
